version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: discorre
      POSTGRES_PASSWORD: 0412
      POSTGRES_DB: pharmacy
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d:rw
    ports:
      - "5432:5432"
    
    
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
