version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pharmacy_db
    environment:
      POSTGRES_USER: discorre
      POSTGRES_PASSWORD: 0412
      POSTGRES_DB: pharmacy_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pharmacy-network
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: pharmacy_api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: discorre
      DB_PASSWORD: 0412
      DB_NAME: pharmacy_system
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - pharmacy-network

volumes:
  postgres_data:

networks:
  pharmacy-network:
    driver: bridge
